### PR TITLE
Fix nRF52810 build with Arduino and SPI/I2C

### LINKED ISSUE #50: nrf52810 Compilation Error Resulting From Typo in boards.txt
As the library is right now, I get `#error "Device must be defined. See nrf.h."`

In boards.txt, I believe line 1977

 `Generic_nRF52810.build.extra_flags=-DNRF52_SERIES -DnRF52810_XXAA {bootloader.flags} -DCONFIG_NIMBLE_CPP_LOG_LEVEL={build.cpp_debug} {build.nimble_flags}`

should be changed to 

 `Generic_nRF52810.build.extra_flags=-DNRF52_SERIES -DNRF52810_XXAA {bootloader.flags} -DCONFIG_NIMBLE_CPP_LOG_LEVEL={build.cpp_debug} {build.nimble_flags}`

### PR DESCRIPTION
**Pull request by h2zero**
Fixes #50, #52

@jackb60

### CODE REVIEW

**Comment by jackb60** [comment]
This appears to break I2C compatibility with the NRF52832. When attempting to compile for NRF52832, I get 
```
[My sketch location.ino]: undefined reference to `Wire'
collect2.exe: error: ld returned 1 exit status
```

It isn't an issue with my sketch, as it compiles fine for NRF52832 with the previous Wire_nRF52.cpp

Works for NRF52810 though.

I'll see if I can figure out the problem. Thank you for this library and the fixes.

**Comment by jackb60** [comment]
For whatever reason, changing line 402 in Wire_nRF52.cpp from
`#if defined(SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQn)` to 
`#if defined(NRF_TWIM1)`
fixed the issue. Now it works for both NRF52810 and NRF52832.

**Comment by h2zero** [comment]
Thanks! I'll make some adjustments.

**Comment by jackb60** [comment]
Looks good. I wonder if you also want to change line 411 in Wire_nRF52.cpp from 
`#if defined(SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQn)` to
`#if defined(NRF_TWIM1)` given the previous issue with `SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQn`

**Comment by h2zero** [comment]
Done, this should work now.

**Comment by h2zero** [comment]
> Looks good. I wonder if you also want to change line 411 in Wire_nRF52.cpp from `#if defined(SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQn)` to `#if defined(NRF_TWIM1)` given the previous issue with `SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQn`

Sorry I missed this comment, yes that seems better for sure at this moment as that doesn't look to actually be `#defined` anywhere but is instead an enum value. For now I will use your suggestion but look to change it in the future if it no longer discriminates accurately enough.

Thanks for all the help!!!

**Comment by h2zero** [comment]
@jackb60 Have you tested this with any devices connected to SPI/I2C? Would be great to know that its working as well as compiling 😄

**Comment by jackb60** [comment]
Yes I have devices attached to both SPI and I2C and they are working (tested with NRF52810).

**Comment by h2zero** [comment]
Perfect, I will merge this then. Thanks again!

**Pull request merged**
